### PR TITLE
temp test fixing depends for playground

### PR DESCRIPTION
**Pull request by bhamacher**
Signed-off-by: bhamacher <b.hamacher@zera.de>

### CODE REVIEW

**Comment by schnitzeltony** [comment]
I did:

* build and install on target
* run vf-qmllibs-examples: same as soon as I press a button (tested all), application complains for missing qrc:/..
* delete libvfnetworkmanager.so*: same application starts and all buttons just complain for missing qrc:/..

**Comment by bhamacher** [comment]
call readelf -d vf-qmllibs-examples (you can do this in your oe work dir)

The output should look like this:

Dynamic section at offset 0x6ce8 contains 41 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Quick.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Qml.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5DBus.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Xml.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Widgets.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libvfnetworkmanager.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libanmlib.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libnotificationmanager.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Network.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Gui.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libQt5Core.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libKF5NetworkManagerQt.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libKF5ModemManagerQt.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libSortFilterProxyModelCmake.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

**Comment by schnitzeltony** [comment]
I think it is the --as-needed in LDFLAGS. It can be overridden by ASNEEDED = ""  - build is running...

**Comment by bhamacher** [comment]
Cross-Prelink: Prelinking is the process of pre-computing the load addresses and link tables generated by the dynamic linker as compared to doing this at runtime. Doing this ahead of time results in performance improvements when the application is launched and reduced memory usage for libraries shared by many applications.

Historically, cross-prelink is a variant of prelink, which was conceived by Jakub Jelínek a number of years ago. Both prelink and cross-prelink are maintained in the same repository albeit on separate branches. By providing an emulated runtime dynamic linker (i.e. glibc-derived ld.so emulation), the cross-prelink project extends the prelink software’s ability to prelink a sysroot environment. Additionally, the cross-prelink software enables the ability to work in sysroot style environments.

The dynamic linker determines standard load address calculations based on a variety of factors such as mapping addresses, library usage, and library function conflicts. The prelink tool uses this information, from the dynamic linker, to determine unique load addresses for executable and linkable format (ELF) binaries that are shared libraries and dynamically linked. The prelink tool modifies these ELF binaries with the pre-computed information. The result is faster loading and often lower memory consumption because more of the library code can be re-used from shared Copy-On-Write (COW) pages.

The original upstream prelink project only supports running prelink on the end target device due to the reliance on the target device’s dynamic linker. This restriction causes issues when developing a cross-compiled system. The cross-prelink adds a synthesized dynamic loader that runs on the host, thus permitting cross-prelinking without ever having to run on a read-write target filesystem.

**Comment by schnitzeltony** [comment]
ASNEEDED = "" + 386986c248e070140f48ebd3c37e6ac7e03ddd8e did the trick

**Pull request closed without merging**
